$axure.loadCurrentPage({
  "url":"指挥一点通web管理端说明.html",
  "generationDate":new Date(1484019367871.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"Number"],
  "page":{
    "packageId":"47a81530410b474ab002d03fe2d3ce26",
    "type":"Axure:Page",
    "name":"指挥一点通WEB管理端说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"547aa381a00e4098bd61270538a4215b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":55},
            "size":{
              "width":149,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b351a32fc71d4e8cb563f9876e6c98b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":55},
                "size":{
                  "width":149,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88b14457f06f47a5939c2ec8a20d86c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":119},
            "size":{
              "width":424,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3327743e247341979151743aa3ef5016",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":119},
                "size":{
                  "width":424,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c050c0fe5004243820fa14324d7a996",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":264},
            "size":{
              "width":383,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98bc797eed5c4c1e990e8e47a7c8cff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":264},
                "size":{
                  "width":383,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78234a3143544cbf995b970cc02425ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":399},
            "size":{
              "width":383,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"717a1532dbd643d79ac32ab5896384a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":399},
                "size":{
                  "width":383,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b0a0e557ed7474892307fd506d1736b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":530},
            "size":{
              "width":383,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"306a607a1ebe409b889635909d7801ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":530},
                "size":{
                  "width":383,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b86b28e95123476e9132bbc6d9a6afac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":1053},
            "size":{
              "width":501,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af7ac659184b4ce6b3ba771374a0faa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":1053},
                "size":{
                  "width":501,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf34327909c943508a86db90710761b8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":1115},
            "size":{
              "width":787,
              "height":325}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50445dfeae344d7999c58763f70ae8cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":1115},
                "size":{
                  "width":787,
                  "height":325}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/指挥一点通web管理端说明/u12.png"}},
{
          "id":"a4690a98b934439d860aa91ef918ebc8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":925,
              "y":1118},
            "size":{
              "width":65,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF2F832F}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/指挥一点通web管理端说明/u14_line.png"}},
{
          "id":"db371eb720624b4d9e7cfb7eedbcae9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":1115},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d80ee2ceccc4eaa9e8c5a797bae48e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":1115},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c296719e2644b9fb68101a2fed111b3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":1237},
            "size":{
              "width":220,
              "height":10},
            "rotation":"355",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/指挥一点通web管理端说明/u17_start.png",
            "end~":"images/指挥一点通web管理端说明/u17_end.png",
            "line~":"images/指挥一点通web管理端说明/u17_line.png"}},
{
          "id":"fbe203f6744f48d6aafd4011d4abe4b7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":1302},
            "size":{
              "width":159,
              "height":10},
            "rotation":"84",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/指挥一点通web管理端说明/u18_start.png",
            "end~":"images/指挥一点通web管理端说明/u18_end.png",
            "line~":"images/指挥一点通web管理端说明/u18_line.png"}},
{
          "id":"3424cfa6c37b40abb4ac81bb733215aa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":346,
              "y":1364},
            "size":{
              "width":166,
              "height":10},
            "rotation":"351",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/指挥一点通web管理端说明/u17_start.png",
            "end~":"images/指挥一点通web管理端说明/u17_end.png",
            "line~":"images/指挥一点通web管理端说明/u19_line.png"}},
{
          "id":"500117a3dfc04aef9068935d238b0e9a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":1338},
            "size":{
              "width":166,
              "height":10},
            "rotation":"351",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/指挥一点通web管理端说明/u17_start.png",
            "end~":"images/指挥一点通web管理端说明/u17_end.png",
            "line~":"images/指挥一点通web管理端说明/u19_line.png"}},
{
          "id":"06a16210568c40d99aafadc615e90fb6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":1269},
            "size":{
              "width":129,
              "height":10},
            "rotation":"84",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/指挥一点通web管理端说明/u21_start.png",
            "end~":"images/指挥一点通web管理端说明/u21_end.png",
            "line~":"images/指挥一点通web管理端说明/u21_line.png"}},
{
          "id":"6d82e721c6d64b3c9d4cf39f63a9fd7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":642,
              "y":1201},
            "size":{
              "width":198,
              "height":10},
            "rotation":"355",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/指挥一点通web管理端说明/u17_start.png",
            "end~":"images/指挥一点通web管理端说明/u17_end.png",
            "line~":"images/指挥一点通web管理端说明/u22_line.png"}},
{
          "id":"0f697d2d30174c31aaae9ed633cbcad1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1135,
              "y":1118},
            "size":{
              "width":65,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/指挥一点通web管理端说明/u23_line.png"}},
{
          "id":"399a6637b4e945d5a3b160f537c4cfcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1210,
              "y":1115},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a106fbebc8c4d989da826208e4e49e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1210,
                  "y":1115},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac8257bc81844e43aeb9b50b68051897",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":115,
              "y":1257},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0eb99945c5a845f59f868d907e09a428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":115,
                  "y":1257},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f82ec9c8b82b4bd2905a74ec9337299b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":345,
              "y":1211},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d93c905855c494d9057fa7004a772c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":345,
                  "y":1211},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"629fd5f4f14f4048ab234e6d8c5ff9fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":336,
              "y":1409},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a9c760ccda4569a1a3ba640f36a6a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":336,
                  "y":1409},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdf73058db3e4387af65bd69669df070",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":495,
              "y":1371},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d25fa50db174f778b6703f8e2aa15b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":495,
                  "y":1371},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f76826ed8ed84be0a7a27fc06b7edb06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":676,
              "y":1325},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1495aa54a52d4c178807383c6b9638d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":676,
                  "y":1325},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"690cd89283a44f85a40c0d87ac8b6e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":632,
              "y":1183},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b25d3d3db1e44eba61aecb89bda26dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":632,
                  "y":1183},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9361277db4d44551aac9b44b832cd5a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":840,
              "y":1179},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fb285c6ca5945feb614d4d368ec37d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":840,
                  "y":1179},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2ea42198e2b4b3b9c42051e952ac600",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":805,
              "y":1151},
            "size":{
              "width":80,
              "height":80},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9900CC},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75ac086719d44148b73be4df0ebf9dc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":805,
                  "y":1151},
                "size":{
                  "width":80,
                  "height":80},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9900CC},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/指挥一点通web管理端说明/u40.png"}},
{
          "id":"b71e508661ca4edd84094559677131b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":925,
              "y":1151},
            "size":{
              "width":250,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e41b4a4a1fe4e41ad2e6f549d999a06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":925,
                  "y":1151},
                "size":{
                  "width":250,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/指挥一点通web管理端说明/u42.png"}},
{
          "id":"366b9cdb3f5f4a2d9513eaeeedde8b3f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":885,
              "y":1220},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"302fd0a516ab45a99f95ebcf5b90fdd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":885,
                  "y":1220},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}]},
{
          "id":"466eed5848654ab8b46fa649903448d4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1060,
              "y":1253},
            "size":{
              "width":10,
              "height":40},
            "rotation":"352"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/指挥一点通web管理端说明/u46_start.png",
            "end~":"images/指挥一点通/u319_end.png",
            "line~":"images/指挥一点通web管理端说明/u46_line.png"}},
{
          "id":"3e6e17c116f04393a9149817f67493a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1004,
              "y":1265},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d3950f7ce0747efbe2a5a88f8040f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1004,
                  "y":1265},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b1df77675804552b693e4a10795f0cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":925,
              "y":1401},
            "size":{
              "width":250,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef117aec98e344d4b89a3c88aff563b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":925,
                  "y":1401},
                "size":{
                  "width":250,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8db3718cebaa4b358dd441e459fa4864",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":1469},
            "size":{
              "width":825,
              "height":356}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7318479b9a324836a3905d03dfa345e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":1469},
                "size":{
                  "width":825,
                  "height":356}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/指挥一点通web管理端说明/u51.png"}},
{
          "id":"9ebf0c5c42d94011b5e6c284d57b17c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":668},
            "size":{
              "width":373,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fc7a2213c0844f6a444b4be460a25bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":668},
                "size":{
                  "width":373,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e0d60c598484770a98258d37e679e9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":744},
            "size":{
              "width":383,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04d067c3c69549dba7c6656a308a7fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":744},
                "size":{
                  "width":383,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "547aa381a00e4098bd61270538a4215b":{
      "scriptId":"u0"},
    "b351a32fc71d4e8cb563f9876e6c98b4":{
      "scriptId":"u1"},
    "88b14457f06f47a5939c2ec8a20d86c6":{
      "scriptId":"u2"},
    "3327743e247341979151743aa3ef5016":{
      "scriptId":"u3"},
    "4c050c0fe5004243820fa14324d7a996":{
      "scriptId":"u4"},
    "98bc797eed5c4c1e990e8e47a7c8cff4":{
      "scriptId":"u5"},
    "78234a3143544cbf995b970cc02425ec":{
      "scriptId":"u6"},
    "717a1532dbd643d79ac32ab5896384a0":{
      "scriptId":"u7"},
    "6b0a0e557ed7474892307fd506d1736b":{
      "scriptId":"u8"},
    "306a607a1ebe409b889635909d7801ca":{
      "scriptId":"u9"},
    "b86b28e95123476e9132bbc6d9a6afac":{
      "scriptId":"u10"},
    "af7ac659184b4ce6b3ba771374a0faa7":{
      "scriptId":"u11"},
    "bf34327909c943508a86db90710761b8":{
      "scriptId":"u12"},
    "50445dfeae344d7999c58763f70ae8cf":{
      "scriptId":"u13"},
    "a4690a98b934439d860aa91ef918ebc8":{
      "scriptId":"u14"},
    "db371eb720624b4d9e7cfb7eedbcae9e":{
      "scriptId":"u15"},
    "4d80ee2ceccc4eaa9e8c5a797bae48e6":{
      "scriptId":"u16"},
    "1c296719e2644b9fb68101a2fed111b3":{
      "scriptId":"u17"},
    "fbe203f6744f48d6aafd4011d4abe4b7":{
      "scriptId":"u18"},
    "3424cfa6c37b40abb4ac81bb733215aa":{
      "scriptId":"u19"},
    "500117a3dfc04aef9068935d238b0e9a":{
      "scriptId":"u20"},
    "06a16210568c40d99aafadc615e90fb6":{
      "scriptId":"u21"},
    "6d82e721c6d64b3c9d4cf39f63a9fd7e":{
      "scriptId":"u22"},
    "0f697d2d30174c31aaae9ed633cbcad1":{
      "scriptId":"u23"},
    "399a6637b4e945d5a3b160f537c4cfcc":{
      "scriptId":"u24"},
    "0a106fbebc8c4d989da826208e4e49e9":{
      "scriptId":"u25"},
    "ac8257bc81844e43aeb9b50b68051897":{
      "scriptId":"u26"},
    "0eb99945c5a845f59f868d907e09a428":{
      "scriptId":"u27"},
    "f82ec9c8b82b4bd2905a74ec9337299b":{
      "scriptId":"u28"},
    "9d93c905855c494d9057fa7004a772c2":{
      "scriptId":"u29"},
    "629fd5f4f14f4048ab234e6d8c5ff9fb":{
      "scriptId":"u30"},
    "10a9c760ccda4569a1a3ba640f36a6a6":{
      "scriptId":"u31"},
    "cdf73058db3e4387af65bd69669df070":{
      "scriptId":"u32"},
    "7d25fa50db174f778b6703f8e2aa15b8":{
      "scriptId":"u33"},
    "f76826ed8ed84be0a7a27fc06b7edb06":{
      "scriptId":"u34"},
    "1495aa54a52d4c178807383c6b9638d0":{
      "scriptId":"u35"},
    "690cd89283a44f85a40c0d87ac8b6e97":{
      "scriptId":"u36"},
    "3b25d3d3db1e44eba61aecb89bda26dc":{
      "scriptId":"u37"},
    "9361277db4d44551aac9b44b832cd5a1":{
      "scriptId":"u38"},
    "2fb285c6ca5945feb614d4d368ec37d7":{
      "scriptId":"u39"},
    "e2ea42198e2b4b3b9c42051e952ac600":{
      "scriptId":"u40"},
    "75ac086719d44148b73be4df0ebf9dc9":{
      "scriptId":"u41"},
    "b71e508661ca4edd84094559677131b3":{
      "scriptId":"u42"},
    "2e41b4a4a1fe4e41ad2e6f549d999a06":{
      "scriptId":"u43"},
    "366b9cdb3f5f4a2d9513eaeeedde8b3f":{
      "scriptId":"u44"},
    "302fd0a516ab45a99f95ebcf5b90fdd9":{
      "scriptId":"u45"},
    "466eed5848654ab8b46fa649903448d4":{
      "scriptId":"u46"},
    "3e6e17c116f04393a9149817f67493a4":{
      "scriptId":"u47"},
    "4d3950f7ce0747efbe2a5a88f8040f9d":{
      "scriptId":"u48"},
    "8b1df77675804552b693e4a10795f0cc":{
      "scriptId":"u49"},
    "ef117aec98e344d4b89a3c88aff563b2":{
      "scriptId":"u50"},
    "8db3718cebaa4b358dd441e459fa4864":{
      "scriptId":"u51"},
    "7318479b9a324836a3905d03dfa345e8":{
      "scriptId":"u52"},
    "9ebf0c5c42d94011b5e6c284d57b17c9":{
      "scriptId":"u53"},
    "2fc7a2213c0844f6a444b4be460a25bb":{
      "scriptId":"u54"},
    "9e0d60c598484770a98258d37e679e9d":{
      "scriptId":"u55"},
    "04d067c3c69549dba7c6656a308a7fbe":{
      "scriptId":"u56"}}});