$axure.loadCurrentPage({
  "url":"公众号进入后主页.html",
  "generationDate":new Date(1484019367024.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"Number"],
  "page":{
    "packageId":"b641e024a5f544f4ae844b476a1fe4b3",
    "type":"Axure:Page",
    "name":"公众号进入后主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0797970c0c894300b738707a858ffb10",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":90},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4295ec0cab214488a50648ef7c7ad29b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":90},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u0.png"}},
{
          "id":"d938d35872ae4aaa83969e84e62a0591",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF21292C},
            "location":{
              "x":90,
              "y":112},
            "size":{
              "width":320,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF21292C}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124e8f3ca1214e8e8f508ecbc9e1f604",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF21292C},
                "location":{
                  "x":90,
                  "y":112},
                "size":{
                  "width":320,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF21292C}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u2.png"}},
{
          "id":"0568eba59cf34badb28b109d18a06a9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":126},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35175fff95f24fd488014c2f5fb11912",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":126},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u4.png"}},
{
          "id":"9613a7822a4742c884f2134b26bbb753",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":122},
            "size":{
              "width":10,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF131C1C}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/公众号进入后主页/u6_line.png"}},
{
          "id":"971e7ab91ea741f5a640925490cf15d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":148,
              "y":124},
            "size":{
              "width":166,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5bd7bf6b45746d6b4b54394b8b696e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":124},
                "size":{
                  "width":166,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3af7d0c671f4f28baa3e25d965d4071",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":373,
              "y":122},
            "size":{
              "width":23,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ce36e3d3c24c6cbb2f8fc7db5dcfb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":373,
                  "y":122},
                "size":{
                  "width":23,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u9.png"}},
{
          "id":"05a3913f191f4d9faec21b088ac7e803",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEBEBEB},
            "location":{
              "x":90,
              "y":155},
            "size":{
              "width":320,
              "height":471},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEBEBEB}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40249085f2ee426b8cb1fef6758cec42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEBEBEB},
                "location":{
                  "x":90,
                  "y":155},
                "size":{
                  "width":320,
                  "height":471},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEBEBEB}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u11.png"}},
{
          "id":"eaf04abc4b26423e89cf08aa8271c832",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":215,
              "y":165},
            "size":{
              "width":70,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f1e05a9ead4cf8985da12ee6356913",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":215,
                  "y":165},
                "size":{
                  "width":70,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u13.png"}},
{
          "id":"6930743b5e5945f195e8795ef2bb87b7",
          "label":"Bottom-输入",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":90,
              "y":582},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7b2e845fff3b41d2a21cf03571e4393d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b5804620fe874464a4f1624604f95d9f",
                  "label":"",
                  "parentDynamicPanel":"6930743b5e5945f195e8795ef2bb87b7",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c2319ac8d88a4dc4a546e8649cb4aada",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6930743b5e5945f195e8795ef2bb87b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/公众号进入后主页/u16.png"}},
{
                  "id":"06aef28042a548fb98a250c699d6152d",
                  "label":"",
                  "parentDynamicPanel":"6930743b5e5945f195e8795ef2bb87b7",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":4},
                    "size":{
                      "width":41,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94fecb9e5ca64b45ae0cb4b903ee0f51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6930743b5e5945f195e8795ef2bb87b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":4},
                        "size":{
                          "width":41,
                          "height":36}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 Bottom-输入 向下滑动 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["6930743b5e5945f195e8795ef2bb87b7"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":200,
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待200毫秒",
                              "waitTime":200},
{
                              "action":"fadeWidget",
                              "description":"显示 Bottom-菜单 向上滑动 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["a6d12e94d10146a8bd08e01b72c5bf0c"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":200,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u18.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"bf0ad5821b314d91828936f649614d7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "lineSpacing":"20px",
            "location":{
              "x":140,
              "y":196},
            "size":{
              "width":210,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5254c546a7f64dbaa447e210e75a1b49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "lineSpacing":"20px",
                "location":{
                  "x":140,
                  "y":196},
                "size":{
                  "width":210,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u20.png"}},
{
          "id":"1845303b0bce4c338af5e8283e74d0a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":253},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9219cfa3fde425ab8100c71a16ff9f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":366,
                  "y":253},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u22.png"}},
{
          "id":"69370a0931854efd8e95cf6be594e69c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "fill":{
              "fillType":"solid",
              "color":0xFF66CC33},
            "location":{
              "x":317,
              "y":253},
            "size":{
              "width":43,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a90c9a69c29b4fcf860c09e9f5f80c7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66CC33},
                "location":{
                  "x":317,
                  "y":253},
                "size":{
                  "width":43,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u24.png"}},
{
          "id":"a6d12e94d10146a8bd08e01b72c5bf0c",
          "label":"Bottom-菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":582},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"3c89b386db6a44448b6ce6589589285f",
              "label":"菜单",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"95ebea49015a45ee80242ddfc5babf0f",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4ae5e5c1af8e470cb5038758d9bfd217",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/公众号进入后主页/u16.png"}},
{
                  "id":"a376d1ef20b845f5a7e5a7a834a91c41",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":9},
                    "size":{
                      "width":26,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8762277067244ba8a7af71cc786bc6a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":9},
                        "size":{
                          "width":26,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 Bottom-菜单 向下滑动 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["a6d12e94d10146a8bd08e01b72c5bf0c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":200,
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待200毫秒",
                              "waitTime":200},
{
                              "action":"fadeWidget",
                              "description":"显示 Bottom-输入 向上滑动 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["6930743b5e5945f195e8795ef2bb87b7"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":200,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u29.png"}},
{
                  "id":"4fcaaa2465654bd68158b9aee8a265a9",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "location":{
                      "x":47,
                      "y":1},
                    "size":{
                      "width":91,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b36da7aafa0459fb73d18e01c59ca66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "location":{
                          "x":47,
                          "y":1},
                        "size":{
                          "width":91,
                          "height":43},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1<br> (If visibility of 资讯 = 假)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetVisibility",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["32bcc22cdbaa4cd992f61e3df517fb18"]}]},
                            "rightExpr":{
                              "exprType":"booleanLiteral",
                              "value":false}},
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 资讯 淡入淡出 200 毫秒 置于顶层",
                              "objectsToFades":[{
                                  "objectPath":["32bcc22cdbaa4cd992f61e3df517fb18"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"front"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 捐赠 淡入淡出 200 毫秒,<br>活动 淡入淡出 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["512db40fabaa4067b119e1a9c7086fd9"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"none"}}},
{
                                  "objectPath":["8ec0cf5e0bce44468fc0bdec0a1fab86"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"none"}}}]}]},
{
                          "description":"用例 2<br> (Else If True)",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 资讯 淡入淡出 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["32bcc22cdbaa4cd992f61e3df517fb18"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u31.png",
                    "mouseDown~":"images/公众号进入后主页/u31_mouseDown.png"}},
{
                  "id":"0b49e34967784d54887eee33bd96333e",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "location":{
                      "x":138,
                      "y":1},
                    "size":{
                      "width":91,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21b8f44be35b4c9a962e98a6002b9ed0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "location":{
                          "x":138,
                          "y":1},
                        "size":{
                          "width":91,
                          "height":43},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1<br> (If visibility of 捐赠 = 假)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetVisibility",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["512db40fabaa4067b119e1a9c7086fd9"]}]},
                            "rightExpr":{
                              "exprType":"booleanLiteral",
                              "value":false}},
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 捐赠 淡入淡出 200 毫秒 置于顶层,<br>隐藏 资讯 淡入淡出 200 毫秒,<br>活动 淡入淡出 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["512db40fabaa4067b119e1a9c7086fd9"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"front"}}},
{
                                  "objectPath":["32bcc22cdbaa4cd992f61e3df517fb18"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"none"}}},
{
                                  "objectPath":["8ec0cf5e0bce44468fc0bdec0a1fab86"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"none"}}}]}]},
{
                          "description":"用例 2<br> (Else If True)",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 捐赠 淡入淡出 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["512db40fabaa4067b119e1a9c7086fd9"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u31.png",
                    "mouseDown~":"images/公众号进入后主页/u31_mouseDown.png"}},
{
                  "id":"8c7a0c5048dc46eba4a92c519be1ef3f",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "location":{
                      "x":229,
                      "y":1},
                    "size":{
                      "width":91,
                      "height":43},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"37a84337b932415693db9c97527d230f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "location":{
                          "x":229,
                          "y":1},
                        "size":{
                          "width":91,
                          "height":43},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1<br> (If visibility of 活动 = 假)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetVisibility",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["8ec0cf5e0bce44468fc0bdec0a1fab86"]}]},
                            "rightExpr":{
                              "exprType":"booleanLiteral",
                              "value":false}},
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 活动 淡入淡出 200 毫秒 置于顶层",
                              "objectsToFades":[{
                                  "objectPath":["8ec0cf5e0bce44468fc0bdec0a1fab86"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"front"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 捐赠 淡入淡出 200 毫秒,<br>资讯 淡入淡出 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["512db40fabaa4067b119e1a9c7086fd9"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"none"}}},
{
                                  "objectPath":["32bcc22cdbaa4cd992f61e3df517fb18"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"none"}}}]}]},
{
                          "description":"用例 2<br> (Else If True)",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 活动 淡入淡出 200 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["8ec0cf5e0bce44468fc0bdec0a1fab86"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":200,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u31.png",
                    "mouseDown~":"images/公众号进入后主页/u31_mouseDown.png"}},
{
                  "id":"2127b6defb6b4ade8ef2dc2893c8e90d",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":132,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":44},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/公众号进入后主页/u37_line.png"}},
{
                  "id":"3697e0065b8a4805b90276e3330f9dca",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":222.75,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":44},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD9D9D9}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/公众号进入后主页/u37_line.png"}},
{
                  "id":"1a8454cb851643798bc5c8d414e31c0b",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":32},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"654225c0e0684302b35322be739cf712",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":32},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/公众号进入后主页/u39.png"}},
{
                  "id":"2f96ce35045647edad9b2dbc22da8306",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":216,
                      "y":32},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c97f3f8f1b44c18bc010c6d6d0ea80e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":216,
                          "y":32},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/公众号进入后主页/u39.png"}},
{
                  "id":"ce8c9a0bcdb147d4ab8dcebb127a53fd",
                  "label":"",
                  "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":308,
                      "y":32},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c6d67d8697b04c1c8ed5904453c7e079",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a6d12e94d10146a8bd08e01b72c5bf0c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":308,
                          "y":32},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/公众号进入后主页/u39.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"32bcc22cdbaa4cd992f61e3df517fb18",
          "label":"资讯",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":136,
              "y":494},
            "size":{
              "width":92,
              "height":88},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f60e3afc728346bbab7426003c011c64",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f80a8258b734490a9fcf56476a676b1f",
                  "label":"",
                  "parentDynamicPanel":"32bcc22cdbaa4cd992f61e3df517fb18",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "size":{
                      "width":92,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a563864c6c1a4fb98fa36c01f665e247",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32bcc22cdbaa4cd992f61e3df517fb18",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "size":{
                          "width":92,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一点登记",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u46.png",
                    "mouseDown~":"images/公众号进入后主页/u46_mouseDown.png"}},
{
                  "id":"fe90b1582e284c489f0826bbc9170250",
                  "label":"",
                  "parentDynamicPanel":"32bcc22cdbaa4cd992f61e3df517fb18",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "location":{
                      "x":0,
                      "y":44},
                    "size":{
                      "width":92,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4f99bfd375a4df681f2728406014fef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"32bcc22cdbaa4cd992f61e3df517fb18",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "location":{
                          "x":0,
                          "y":44},
                        "size":{
                          "width":92,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一点办证",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u46.png",
                    "mouseDown~":"images/公众号进入后主页/u46_mouseDown.png"}},
{
                  "id":"2eb7952ae08c43699b4821ed23f22083",
                  "label":"",
                  "parentDynamicPanel":"32bcc22cdbaa4cd992f61e3df517fb18",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":92,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD8D8D8}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/公众号进入后主页/u50_line.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"512db40fabaa4067b119e1a9c7086fd9",
          "label":"捐赠",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":227,
              "y":406},
            "size":{
              "width":92,
              "height":177},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0b8681017b614780987118aacaea0dd8",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a521b81ca0b947038dc6b3022bc52643",
                  "label":"",
                  "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "size":{
                      "width":92,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0316afabcb445c6a8b5bdf43f23c61a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "size":{
                          "width":92,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一点报警",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u46.png",
                    "mouseDown~":"images/公众号进入后主页/u46_mouseDown.png"}},
{
                  "id":"44491fe4e1bc474d835ab8524b151184",
                  "label":"",
                  "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "location":{
                      "x":0,
                      "y":44},
                    "size":{
                      "width":92,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c402b5b035e7460e8b37dedeeb1b0e36",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "location":{
                          "x":0,
                          "y":44},
                        "size":{
                          "width":92,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一点约警",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u46.png",
                    "mouseDown~":"images/公众号进入后主页/u46_mouseDown.png"}},
{
                  "id":"b1237133c7b943459f4ef33ddb830f3d",
                  "label":"",
                  "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":92,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD8D8D8}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/公众号进入后主页/u50_line.png"}},
{
                  "id":"91ce7c5b7f2f45cbbc01de2e7d48c980",
                  "label":"",
                  "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "location":{
                      "x":0,
                      "y":88},
                    "size":{
                      "width":92,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e647d283c5aa43d3984f9830ae61c9ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":92,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一点举报",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u46.png",
                    "mouseDown~":"images/公众号进入后主页/u46_mouseDown.png"}},
{
                  "id":"ab8a4d811f184fc1a5156d451d6c7c32",
                  "label":"",
                  "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":83},
                    "size":{
                      "width":92,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD8D8D8}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/公众号进入后主页/u50_line.png"}},
{
                  "id":"57b8d8e038ba4bf198caaee5acff2f28",
                  "label":"",
                  "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "location":{
                      "x":0,
                      "y":132},
                    "size":{
                      "width":92,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65bce7e4fb014974a7687e91fd520987",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "location":{
                          "x":0,
                          "y":132},
                        "size":{
                          "width":92,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一点悬赏",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u46.png",
                    "mouseDown~":"images/公众号进入后主页/u46_mouseDown.png"}},
{
                  "id":"a342508be63d4342af4ac29bdedc48a0",
                  "label":"",
                  "parentDynamicPanel":"512db40fabaa4067b119e1a9c7086fd9",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":127},
                    "size":{
                      "width":92,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD8D8D8}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/公众号进入后主页/u50_line.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"8ec0cf5e0bce44468fc0bdec0a1fab86",
          "label":"活动",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":314,
              "y":494},
            "size":{
              "width":92,
              "height":88},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e71cbd6237384a2da4f496539af33057",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8d704c111bbc409aa237e04b9c617c15",
                  "label":"",
                  "parentDynamicPanel":"8ec0cf5e0bce44468fc0bdec0a1fab86",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "size":{
                      "width":92,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1521ab301a43456fadaab0ced55d3205",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8ec0cf5e0bce44468fc0bdec0a1fab86",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "size":{
                          "width":92,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一点建议",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u46.png",
                    "mouseDown~":"images/公众号进入后主页/u46_mouseDown.png"}},
{
                  "id":"e905d8e671ce40cab156cb370a4d57cf",
                  "label":"",
                  "parentDynamicPanel":"8ec0cf5e0bce44468fc0bdec0a1fab86",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseDown":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFD8D8D8}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF},
                    "location":{
                      "x":0,
                      "y":44},
                    "size":{
                      "width":92,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e2317202abf48ad8247800ddc9b3b41",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8ec0cf5e0bce44468fc0bdec0a1fab86",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "stateStyles":{
                          "mouseDown":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF},
                        "location":{
                          "x":0,
                          "y":44},
                        "size":{
                          "width":92,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 一点赞警",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公众号进入后主页/u46.png",
                    "mouseDown~":"images/公众号进入后主页/u46_mouseDown.png"}},
{
                  "id":"f036208fe67e4b6b8b97a5ba22535eea",
                  "label":"",
                  "parentDynamicPanel":"8ec0cf5e0bce44468fc0bdec0a1fab86",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":39},
                    "size":{
                      "width":92,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD8D8D8}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/公众号进入后主页/u50_line.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"3ba4f24f87a444bcb97c541a634c7fa6",
          "label":"公益常识",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":104,
              "y":324},
            "size":{
              "width":292,
              "height":191},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"935a08af7a5a4d099771b2a500059460",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"93d2e89f1ef0421e91700a28996e890a",
                  "label":"",
                  "parentDynamicPanel":"3ba4f24f87a444bcb97c541a634c7fa6",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":292,
                      "height":191}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a2e98d6aa4c4ba0b50a266267cc98d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3ba4f24f87a444bcb97c541a634c7fa6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":292,
                          "height":191}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/公众号进入后主页/u70.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"58b1bb1bc4d54f7ea5e2f90fa3891746",
          "label":"近期活动",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":104,
              "y":324},
            "size":{
              "width":292,
              "height":191},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"10cb75f86174401d9d4a2965e54f1a1e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d7746469a5e7482dafd8b183489e05d1",
                  "label":"",
                  "parentDynamicPanel":"58b1bb1bc4d54f7ea5e2f90fa3891746",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":292,
                      "height":191}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a767b52533c64a85990bc5e043812f72",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"58b1bb1bc4d54f7ea5e2f90fa3891746",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":292,
                          "height":191}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/公众号进入后主页/u73.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"4d6bed36316a498f91c89a1353e514c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":196},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"747f3f32631f4436a61fe06da2196f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":196},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公众号进入后主页/u75.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0797970c0c894300b738707a858ffb10":{
      "scriptId":"u0"},
    "4295ec0cab214488a50648ef7c7ad29b":{
      "scriptId":"u1"},
    "d938d35872ae4aaa83969e84e62a0591":{
      "scriptId":"u2"},
    "124e8f3ca1214e8e8f508ecbc9e1f604":{
      "scriptId":"u3"},
    "0568eba59cf34badb28b109d18a06a9e":{
      "scriptId":"u4"},
    "35175fff95f24fd488014c2f5fb11912":{
      "scriptId":"u5"},
    "9613a7822a4742c884f2134b26bbb753":{
      "scriptId":"u6"},
    "971e7ab91ea741f5a640925490cf15d6":{
      "scriptId":"u7"},
    "b5bd7bf6b45746d6b4b54394b8b696e0":{
      "scriptId":"u8"},
    "b3af7d0c671f4f28baa3e25d965d4071":{
      "scriptId":"u9"},
    "e9ce36e3d3c24c6cbb2f8fc7db5dcfb5":{
      "scriptId":"u10"},
    "05a3913f191f4d9faec21b088ac7e803":{
      "scriptId":"u11"},
    "40249085f2ee426b8cb1fef6758cec42":{
      "scriptId":"u12"},
    "eaf04abc4b26423e89cf08aa8271c832":{
      "scriptId":"u13"},
    "c9f1e05a9ead4cf8985da12ee6356913":{
      "scriptId":"u14"},
    "6930743b5e5945f195e8795ef2bb87b7":{
      "scriptId":"u15"},
    "b5804620fe874464a4f1624604f95d9f":{
      "scriptId":"u16"},
    "c2319ac8d88a4dc4a546e8649cb4aada":{
      "scriptId":"u17"},
    "06aef28042a548fb98a250c699d6152d":{
      "scriptId":"u18"},
    "94fecb9e5ca64b45ae0cb4b903ee0f51":{
      "scriptId":"u19"},
    "bf0ad5821b314d91828936f649614d7a":{
      "scriptId":"u20"},
    "5254c546a7f64dbaa447e210e75a1b49":{
      "scriptId":"u21"},
    "1845303b0bce4c338af5e8283e74d0a5":{
      "scriptId":"u22"},
    "e9219cfa3fde425ab8100c71a16ff9f1":{
      "scriptId":"u23"},
    "69370a0931854efd8e95cf6be594e69c":{
      "scriptId":"u24"},
    "a90c9a69c29b4fcf860c09e9f5f80c7f":{
      "scriptId":"u25"},
    "a6d12e94d10146a8bd08e01b72c5bf0c":{
      "scriptId":"u26"},
    "95ebea49015a45ee80242ddfc5babf0f":{
      "scriptId":"u27"},
    "4ae5e5c1af8e470cb5038758d9bfd217":{
      "scriptId":"u28"},
    "a376d1ef20b845f5a7e5a7a834a91c41":{
      "scriptId":"u29"},
    "a8762277067244ba8a7af71cc786bc6a":{
      "scriptId":"u30"},
    "4fcaaa2465654bd68158b9aee8a265a9":{
      "scriptId":"u31"},
    "8b36da7aafa0459fb73d18e01c59ca66":{
      "scriptId":"u32"},
    "0b49e34967784d54887eee33bd96333e":{
      "scriptId":"u33"},
    "21b8f44be35b4c9a962e98a6002b9ed0":{
      "scriptId":"u34"},
    "8c7a0c5048dc46eba4a92c519be1ef3f":{
      "scriptId":"u35"},
    "37a84337b932415693db9c97527d230f":{
      "scriptId":"u36"},
    "2127b6defb6b4ade8ef2dc2893c8e90d":{
      "scriptId":"u37"},
    "3697e0065b8a4805b90276e3330f9dca":{
      "scriptId":"u38"},
    "1a8454cb851643798bc5c8d414e31c0b":{
      "scriptId":"u39"},
    "654225c0e0684302b35322be739cf712":{
      "scriptId":"u40"},
    "2f96ce35045647edad9b2dbc22da8306":{
      "scriptId":"u41"},
    "1c97f3f8f1b44c18bc010c6d6d0ea80e":{
      "scriptId":"u42"},
    "ce8c9a0bcdb147d4ab8dcebb127a53fd":{
      "scriptId":"u43"},
    "c6d67d8697b04c1c8ed5904453c7e079":{
      "scriptId":"u44"},
    "32bcc22cdbaa4cd992f61e3df517fb18":{
      "scriptId":"u45"},
    "f80a8258b734490a9fcf56476a676b1f":{
      "scriptId":"u46"},
    "a563864c6c1a4fb98fa36c01f665e247":{
      "scriptId":"u47"},
    "fe90b1582e284c489f0826bbc9170250":{
      "scriptId":"u48"},
    "c4f99bfd375a4df681f2728406014fef":{
      "scriptId":"u49"},
    "2eb7952ae08c43699b4821ed23f22083":{
      "scriptId":"u50"},
    "512db40fabaa4067b119e1a9c7086fd9":{
      "scriptId":"u51"},
    "a521b81ca0b947038dc6b3022bc52643":{
      "scriptId":"u52"},
    "a0316afabcb445c6a8b5bdf43f23c61a":{
      "scriptId":"u53"},
    "44491fe4e1bc474d835ab8524b151184":{
      "scriptId":"u54"},
    "c402b5b035e7460e8b37dedeeb1b0e36":{
      "scriptId":"u55"},
    "b1237133c7b943459f4ef33ddb830f3d":{
      "scriptId":"u56"},
    "91ce7c5b7f2f45cbbc01de2e7d48c980":{
      "scriptId":"u57"},
    "e647d283c5aa43d3984f9830ae61c9ce":{
      "scriptId":"u58"},
    "ab8a4d811f184fc1a5156d451d6c7c32":{
      "scriptId":"u59"},
    "57b8d8e038ba4bf198caaee5acff2f28":{
      "scriptId":"u60"},
    "65bce7e4fb014974a7687e91fd520987":{
      "scriptId":"u61"},
    "a342508be63d4342af4ac29bdedc48a0":{
      "scriptId":"u62"},
    "8ec0cf5e0bce44468fc0bdec0a1fab86":{
      "scriptId":"u63"},
    "8d704c111bbc409aa237e04b9c617c15":{
      "scriptId":"u64"},
    "1521ab301a43456fadaab0ced55d3205":{
      "scriptId":"u65"},
    "e905d8e671ce40cab156cb370a4d57cf":{
      "scriptId":"u66"},
    "0e2317202abf48ad8247800ddc9b3b41":{
      "scriptId":"u67"},
    "f036208fe67e4b6b8b97a5ba22535eea":{
      "scriptId":"u68"},
    "3ba4f24f87a444bcb97c541a634c7fa6":{
      "scriptId":"u69"},
    "93d2e89f1ef0421e91700a28996e890a":{
      "scriptId":"u70"},
    "9a2e98d6aa4c4ba0b50a266267cc98d8":{
      "scriptId":"u71"},
    "58b1bb1bc4d54f7ea5e2f90fa3891746":{
      "scriptId":"u72"},
    "d7746469a5e7482dafd8b183489e05d1":{
      "scriptId":"u73"},
    "a767b52533c64a85990bc5e043812f72":{
      "scriptId":"u74"},
    "4d6bed36316a498f91c89a1353e514c8":{
      "scriptId":"u75"},
    "747f3f32631f4436a61fe06da2196f74":{
      "scriptId":"u76"}}});